name: Build .NET Framework 4.5 App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore YourSolution.sln

      - name: Build solution
        run: msbuild TelegramRAT.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildOutput
          path: |
            **/bin/Release/
            
